### ISSUE TITLE
Export list of recipes and contents

### ISSUE THREAD

**Issue by Popolechien** [openzim/cms#1]
We are starting to have quite a few recipes, it would be extremely useful to be able to export some sort of CSV list of all available contents across languages, e.g. something that can be shared with potential partners with the fields `language`, `title`, and `description`

**Comment by Popolechien** [comment]
Sounds good enough to me.

**Comment by kelson42** [comment]
https://www.convertcsv.com/xml-to-csv.htm semble faire le job. J'ai testé avec https://download.kiwix.org/library/library_zim.xml et le résultatn est convaincant.
