### ISSUE TITLE
All zim produced should have a permalink

### ISSUE THREAD

**Issue by Popolechien** [openzim/cms#2]
Following up on #1 : all zim files produced by the zimfarm have a `zim_name-YYYY-MM.zim` format. However when exporting the list from https://download.kiwix.org/library/library_zim.xml the corresponding link is only valid for 30 more days in most cases (assuming a monthly refresh rate). 

It would be much more convenient and useful if all zim files could have a generic `zim_name.zim` name that redirects to the most up-to-date zim file (we already have this for a number of Wikipedia files, so it's more a matter of scale than doability).

**Comment by kelson42** [comment]
@Popolechien The all have a permalink, just remove the date part and the category subdirectory andyou have permalink.

**Comment by Popolechien** [comment]
@kelson I did some manual editing from the exported .xml and got this: https://docs.google.com/spreadsheets/d/1lWXdwy3OIfZ1Ob2cQR707OMHSva3khTcAXZE9MK9ad8/edit#gid=552567720

I could regexp most of the changes, but any way this export could be somewhat automated to the right format?

**Comment by kelson42** [comment]
@Popolechien Yes, it can, but the quesiton is more is this really worth it because I will have to invest beetween 2-4 hours to get it done. And we will have the CMS in a few months, which should be able to deliver what you need.

**Comment by Popolechien** [comment]
@kelson Then we can wait, the excel sheet will have to do.
