### ISSUE TITLE
Document backup-restore strategy

### ISSUE THREAD

**Issue by rgaudin** [openzim/cms#20]
It's important the CMS is backed up from the start and that we have a easy restoration procedure.

This procedure should be documented on the repo or the Wiki and testable (manually). It should use https://github.com/kiwix/borg-backup/ unless proven not possible.

__Note__: at the moment, we'll have only DB data a no user file

**Comment by kelson42** [comment]
@rgaudin Not sure how this is « special » on CMS, but seems indeed mandatory and necessary before moving to M2.

**Comment by rgaudin** [comment]
DB is backed-up (already was on Sloppy). We need a generic Restore doc on the k8s Wiki. Opening a ticket there.

**Comment by kelson42** [comment]
@rgaudin thx, see https://github.com/kiwix/k8s/issues/14
