### ISSUE TITLE
zimcheck dashboard

### ISSUE THREAD

**Issue by rgaudin** [openzim/cms#78]
All Book entries are created with their respective zimcheck JSON output. Ultimately, we'll use this information in Collections to filter-in/out books.

For the moment, we want to be informed of the status of the ZIM we create. We expect many of them to raise issues but we don't know which ones so it's difficult to act upon.

This ticket thus requires the addition of a new page in the UI with:

- [ ] Condensed stats of zimcheck data: how many books passing, how many don't ; with stats for each kind of errors and maybe the Scrapers that raises them most.

- [ ] a ZIM browser (list with pagination) for the list of all those that don't pass. 

- [x] a zimcheck output visualizer so it's easy an useful instead of the raw JSON output. This Component could be used in Book detail view as well.

**Comment by kelson42** [comment]
@fadiga Any progress on this ticket? This is the last one!
